// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Company struct {
	ID         int64
	Name       string
	Notified   bool
	ImportDate pgtype.Date
}
